### ISSUE TITLE
Improve dependencies

### ISSUE THREAD

**Issue by nonameolsson** [CongenialData/components#23]
At the moment we have not configured our `package.json` correctly. Some packages must be installed in the root project to be able to use the components.

- [x] Include correct type of dependencies #24 
- [ ] Make package work without Font Awesome #25
- [ ] Remove dependency of i18n #26
